<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="11193" started-at="2020-10-30T18:47:27Z" finished-at="2020-10-30T18:47:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="11193" started-at="2020-10-30T18:47:27Z" finished-at="2020-10-30T18:47:38Z">
      <class name="test_scripts.Valid_Login">
        <test-method status="PASS" signature="openappln()[pri:0, instance:test_scripts.Valid_Login@34033bd0]" name="openappln" is-config="true" duration-ms="6837" started-at="2020-10-31T00:17:27Z" finished-at="2020-10-31T00:17:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openappln -->
        <test-method status="FAIL" signature="validlogin()[pri:0, instance:test_scripts.Valid_Login@34033bd0]" name="validlogin" duration-ms="1310" started-at="2020-10-31T00:17:33Z" finished-at="2020-10-31T00:17:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at test_scripts.Valid_Login.validlogin(Valid_Login.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validlogin -->
        <test-method status="PASS" signature="closeappln(org.testng.ITestResult)[pri:0, instance:test_scripts.Valid_Login@34033bd0]" name="closeappln" is-config="true" duration-ms="3026" started-at="2020-10-31T00:17:35Z" finished-at="2020-10-31T00:17:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validlogin status=FAILURE method=Valid_Login.validlogin()[pri:0, instance:test_scripts.Valid_Login@34033bd0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeappln -->
      </class> <!-- test_scripts.Valid_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
